logging:
  level:
    root: info
    it.labtech.platform.api: debug

spring:
  application:
    name: labtech-platform
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://dev00.labtech.it/auth/realms/labtech

server:
  port: ${APPLICATION_HOST_PORT:8080}
  servlet:
    contextPath: /platform

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,metrics,mappings,caches"